// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logininfo.proto

package com.zkartmod;

public final class LoginInfoProtos {
  private LoginInfoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zkart.Login)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 ID = 1;</code>
     * @return The iD.
     */
    int getID();

    /**
     * <code>string mail = 2;</code>
     * @return The mail.
     */
    java.lang.String getMail();
    /**
     * <code>string mail = 2;</code>
     * @return The bytes for mail.
     */
    com.google.protobuf.ByteString
        getMailBytes();

    /**
     * <code>string password = 3;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 3;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code zkart.Login}
   */
  public  static final class Login extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zkart.Login)
      LoginOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Login.newBuilder() to construct.
    private Login(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Login() {
      mail_ = "";
      password_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Login();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Login(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              iD_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              mail_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zkartmod.LoginInfoProtos.internal_static_zkart_Login_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zkartmod.LoginInfoProtos.internal_static_zkart_Login_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zkartmod.LoginInfoProtos.Login.class, com.zkartmod.LoginInfoProtos.Login.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int iD_;
    /**
     * <code>int32 ID = 1;</code>
     * @return The iD.
     */
    public int getID() {
      return iD_;
    }

    public static final int MAIL_FIELD_NUMBER = 2;
    private volatile java.lang.Object mail_;
    /**
     * <code>string mail = 2;</code>
     * @return The mail.
     */
    public java.lang.String getMail() {
      java.lang.Object ref = mail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mail_ = s;
        return s;
      }
    }
    /**
     * <code>string mail = 2;</code>
     * @return The bytes for mail.
     */
    public com.google.protobuf.ByteString
        getMailBytes() {
      java.lang.Object ref = mail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 3;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (iD_ != 0) {
        output.writeInt32(1, iD_);
      }
      if (!getMailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mail_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (iD_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, iD_);
      }
      if (!getMailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mail_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zkartmod.LoginInfoProtos.Login)) {
        return super.equals(obj);
      }
      com.zkartmod.LoginInfoProtos.Login other = (com.zkartmod.LoginInfoProtos.Login) obj;

      if (getID()
          != other.getID()) return false;
      if (!getMail()
          .equals(other.getMail())) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getID();
      hash = (37 * hash) + MAIL_FIELD_NUMBER;
      hash = (53 * hash) + getMail().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zkartmod.LoginInfoProtos.Login parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.LoginInfoProtos.Login parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.LoginInfoProtos.Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.LoginInfoProtos.Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.LoginInfoProtos.Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.LoginInfoProtos.Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.LoginInfoProtos.Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zkartmod.LoginInfoProtos.Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkartmod.LoginInfoProtos.Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zkartmod.LoginInfoProtos.Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkartmod.LoginInfoProtos.Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zkartmod.LoginInfoProtos.Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zkartmod.LoginInfoProtos.Login prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zkart.Login}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zkart.Login)
        com.zkartmod.LoginInfoProtos.LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zkartmod.LoginInfoProtos.internal_static_zkart_Login_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zkartmod.LoginInfoProtos.internal_static_zkart_Login_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zkartmod.LoginInfoProtos.Login.class, com.zkartmod.LoginInfoProtos.Login.Builder.class);
      }

      // Construct using com.zkartmod.LoginInfoProtos.Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        iD_ = 0;

        mail_ = "";

        password_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zkartmod.LoginInfoProtos.internal_static_zkart_Login_descriptor;
      }

      @java.lang.Override
      public com.zkartmod.LoginInfoProtos.Login getDefaultInstanceForType() {
        return com.zkartmod.LoginInfoProtos.Login.getDefaultInstance();
      }

      @java.lang.Override
      public com.zkartmod.LoginInfoProtos.Login build() {
        com.zkartmod.LoginInfoProtos.Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zkartmod.LoginInfoProtos.Login buildPartial() {
        com.zkartmod.LoginInfoProtos.Login result = new com.zkartmod.LoginInfoProtos.Login(this);
        result.iD_ = iD_;
        result.mail_ = mail_;
        result.password_ = password_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zkartmod.LoginInfoProtos.Login) {
          return mergeFrom((com.zkartmod.LoginInfoProtos.Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zkartmod.LoginInfoProtos.Login other) {
        if (other == com.zkartmod.LoginInfoProtos.Login.getDefaultInstance()) return this;
        if (other.getID() != 0) {
          setID(other.getID());
        }
        if (!other.getMail().isEmpty()) {
          mail_ = other.mail_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zkartmod.LoginInfoProtos.Login parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zkartmod.LoginInfoProtos.Login) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int iD_ ;
      /**
       * <code>int32 ID = 1;</code>
       * @return The iD.
       */
      public int getID() {
        return iD_;
      }
      /**
       * <code>int32 ID = 1;</code>
       * @param value The iD to set.
       * @return This builder for chaining.
       */
      public Builder setID(int value) {
        
        iD_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearID() {
        
        iD_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object mail_ = "";
      /**
       * <code>string mail = 2;</code>
       * @return The mail.
       */
      public java.lang.String getMail() {
        java.lang.Object ref = mail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mail = 2;</code>
       * @return The bytes for mail.
       */
      public com.google.protobuf.ByteString
          getMailBytes() {
        java.lang.Object ref = mail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mail = 2;</code>
       * @param value The mail to set.
       * @return This builder for chaining.
       */
      public Builder setMail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mail = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMail() {
        
        mail_ = getDefaultInstance().getMail();
        onChanged();
        return this;
      }
      /**
       * <code>string mail = 2;</code>
       * @param value The bytes for mail to set.
       * @return This builder for chaining.
       */
      public Builder setMailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mail_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 3;</code>
       * @return The password.
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 3;</code>
       * @return The bytes for password.
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 3;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 3;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zkart.Login)
    }

    // @@protoc_insertion_point(class_scope:zkart.Login)
    private static final com.zkartmod.LoginInfoProtos.Login DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zkartmod.LoginInfoProtos.Login();
    }

    public static com.zkartmod.LoginInfoProtos.Login getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Login>
        PARSER = new com.google.protobuf.AbstractParser<Login>() {
      @java.lang.Override
      public Login parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Login(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Login> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Login> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zkartmod.LoginInfoProtos.Login getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AllLoginInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zkart.AllLoginInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .zkart.Login login = 1;</code>
     */
    java.util.List<com.zkartmod.LoginInfoProtos.Login> 
        getLoginList();
    /**
     * <code>repeated .zkart.Login login = 1;</code>
     */
    com.zkartmod.LoginInfoProtos.Login getLogin(int index);
    /**
     * <code>repeated .zkart.Login login = 1;</code>
     */
    int getLoginCount();
    /**
     * <code>repeated .zkart.Login login = 1;</code>
     */
    java.util.List<? extends com.zkartmod.LoginInfoProtos.LoginOrBuilder> 
        getLoginOrBuilderList();
    /**
     * <code>repeated .zkart.Login login = 1;</code>
     */
    com.zkartmod.LoginInfoProtos.LoginOrBuilder getLoginOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code zkart.AllLoginInfo}
   */
  public  static final class AllLoginInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zkart.AllLoginInfo)
      AllLoginInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AllLoginInfo.newBuilder() to construct.
    private AllLoginInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    AllLoginInfo() {
      login_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AllLoginInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AllLoginInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                login_ = new java.util.ArrayList<com.zkartmod.LoginInfoProtos.Login>();
                mutable_bitField0_ |= 0x00000001;
              }
              login_.add(
                  input.readMessage(com.zkartmod.LoginInfoProtos.Login.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          login_ = java.util.Collections.unmodifiableList(login_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zkartmod.LoginInfoProtos.internal_static_zkart_AllLoginInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zkartmod.LoginInfoProtos.internal_static_zkart_AllLoginInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zkartmod.LoginInfoProtos.AllLoginInfo.class, com.zkartmod.LoginInfoProtos.AllLoginInfo.Builder.class);
    }

    public static final int LOGIN_FIELD_NUMBER = 1;
    private java.util.List<com.zkartmod.LoginInfoProtos.Login> login_;
    /**
     * <code>repeated .zkart.Login login = 1;</code>
     */
    public java.util.List<com.zkartmod.LoginInfoProtos.Login> getLoginList() {
      return login_;
    }
    /**
     * <code>repeated .zkart.Login login = 1;</code>
     */
    public java.util.List<? extends com.zkartmod.LoginInfoProtos.LoginOrBuilder> 
        getLoginOrBuilderList() {
      return login_;
    }
    /**
     * <code>repeated .zkart.Login login = 1;</code>
     */
    public int getLoginCount() {
      return login_.size();
    }
    /**
     * <code>repeated .zkart.Login login = 1;</code>
     */
    public com.zkartmod.LoginInfoProtos.Login getLogin(int index) {
      return login_.get(index);
    }
    /**
     * <code>repeated .zkart.Login login = 1;</code>
     */
    public com.zkartmod.LoginInfoProtos.LoginOrBuilder getLoginOrBuilder(
        int index) {
      return login_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < login_.size(); i++) {
        output.writeMessage(1, login_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < login_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, login_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zkartmod.LoginInfoProtos.AllLoginInfo)) {
        return super.equals(obj);
      }
      com.zkartmod.LoginInfoProtos.AllLoginInfo other = (com.zkartmod.LoginInfoProtos.AllLoginInfo) obj;

      if (!getLoginList()
          .equals(other.getLoginList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getLoginCount() > 0) {
        hash = (37 * hash) + LOGIN_FIELD_NUMBER;
        hash = (53 * hash) + getLoginList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zkartmod.LoginInfoProtos.AllLoginInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.LoginInfoProtos.AllLoginInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.LoginInfoProtos.AllLoginInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.LoginInfoProtos.AllLoginInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.LoginInfoProtos.AllLoginInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.LoginInfoProtos.AllLoginInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.LoginInfoProtos.AllLoginInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zkartmod.LoginInfoProtos.AllLoginInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkartmod.LoginInfoProtos.AllLoginInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zkartmod.LoginInfoProtos.AllLoginInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkartmod.LoginInfoProtos.AllLoginInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zkartmod.LoginInfoProtos.AllLoginInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zkartmod.LoginInfoProtos.AllLoginInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zkart.AllLoginInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zkart.AllLoginInfo)
        com.zkartmod.LoginInfoProtos.AllLoginInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zkartmod.LoginInfoProtos.internal_static_zkart_AllLoginInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zkartmod.LoginInfoProtos.internal_static_zkart_AllLoginInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zkartmod.LoginInfoProtos.AllLoginInfo.class, com.zkartmod.LoginInfoProtos.AllLoginInfo.Builder.class);
      }

      // Construct using com.zkartmod.LoginInfoProtos.AllLoginInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLoginFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (loginBuilder_ == null) {
          login_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          loginBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zkartmod.LoginInfoProtos.internal_static_zkart_AllLoginInfo_descriptor;
      }

      @java.lang.Override
      public com.zkartmod.LoginInfoProtos.AllLoginInfo getDefaultInstanceForType() {
        return com.zkartmod.LoginInfoProtos.AllLoginInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.zkartmod.LoginInfoProtos.AllLoginInfo build() {
        com.zkartmod.LoginInfoProtos.AllLoginInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zkartmod.LoginInfoProtos.AllLoginInfo buildPartial() {
        com.zkartmod.LoginInfoProtos.AllLoginInfo result = new com.zkartmod.LoginInfoProtos.AllLoginInfo(this);
        int from_bitField0_ = bitField0_;
        if (loginBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            login_ = java.util.Collections.unmodifiableList(login_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.login_ = login_;
        } else {
          result.login_ = loginBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zkartmod.LoginInfoProtos.AllLoginInfo) {
          return mergeFrom((com.zkartmod.LoginInfoProtos.AllLoginInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zkartmod.LoginInfoProtos.AllLoginInfo other) {
        if (other == com.zkartmod.LoginInfoProtos.AllLoginInfo.getDefaultInstance()) return this;
        if (loginBuilder_ == null) {
          if (!other.login_.isEmpty()) {
            if (login_.isEmpty()) {
              login_ = other.login_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLoginIsMutable();
              login_.addAll(other.login_);
            }
            onChanged();
          }
        } else {
          if (!other.login_.isEmpty()) {
            if (loginBuilder_.isEmpty()) {
              loginBuilder_.dispose();
              loginBuilder_ = null;
              login_ = other.login_;
              bitField0_ = (bitField0_ & ~0x00000001);
              loginBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLoginFieldBuilder() : null;
            } else {
              loginBuilder_.addAllMessages(other.login_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zkartmod.LoginInfoProtos.AllLoginInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zkartmod.LoginInfoProtos.AllLoginInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.zkartmod.LoginInfoProtos.Login> login_ =
        java.util.Collections.emptyList();
      private void ensureLoginIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          login_ = new java.util.ArrayList<com.zkartmod.LoginInfoProtos.Login>(login_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zkartmod.LoginInfoProtos.Login, com.zkartmod.LoginInfoProtos.Login.Builder, com.zkartmod.LoginInfoProtos.LoginOrBuilder> loginBuilder_;

      /**
       * <code>repeated .zkart.Login login = 1;</code>
       */
      public java.util.List<com.zkartmod.LoginInfoProtos.Login> getLoginList() {
        if (loginBuilder_ == null) {
          return java.util.Collections.unmodifiableList(login_);
        } else {
          return loginBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .zkart.Login login = 1;</code>
       */
      public int getLoginCount() {
        if (loginBuilder_ == null) {
          return login_.size();
        } else {
          return loginBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .zkart.Login login = 1;</code>
       */
      public com.zkartmod.LoginInfoProtos.Login getLogin(int index) {
        if (loginBuilder_ == null) {
          return login_.get(index);
        } else {
          return loginBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .zkart.Login login = 1;</code>
       */
      public Builder setLogin(
          int index, com.zkartmod.LoginInfoProtos.Login value) {
        if (loginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLoginIsMutable();
          login_.set(index, value);
          onChanged();
        } else {
          loginBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .zkart.Login login = 1;</code>
       */
      public Builder setLogin(
          int index, com.zkartmod.LoginInfoProtos.Login.Builder builderForValue) {
        if (loginBuilder_ == null) {
          ensureLoginIsMutable();
          login_.set(index, builderForValue.build());
          onChanged();
        } else {
          loginBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zkart.Login login = 1;</code>
       */
      public Builder addLogin(com.zkartmod.LoginInfoProtos.Login value) {
        if (loginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLoginIsMutable();
          login_.add(value);
          onChanged();
        } else {
          loginBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .zkart.Login login = 1;</code>
       */
      public Builder addLogin(
          int index, com.zkartmod.LoginInfoProtos.Login value) {
        if (loginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLoginIsMutable();
          login_.add(index, value);
          onChanged();
        } else {
          loginBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .zkart.Login login = 1;</code>
       */
      public Builder addLogin(
          com.zkartmod.LoginInfoProtos.Login.Builder builderForValue) {
        if (loginBuilder_ == null) {
          ensureLoginIsMutable();
          login_.add(builderForValue.build());
          onChanged();
        } else {
          loginBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zkart.Login login = 1;</code>
       */
      public Builder addLogin(
          int index, com.zkartmod.LoginInfoProtos.Login.Builder builderForValue) {
        if (loginBuilder_ == null) {
          ensureLoginIsMutable();
          login_.add(index, builderForValue.build());
          onChanged();
        } else {
          loginBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zkart.Login login = 1;</code>
       */
      public Builder addAllLogin(
          java.lang.Iterable<? extends com.zkartmod.LoginInfoProtos.Login> values) {
        if (loginBuilder_ == null) {
          ensureLoginIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, login_);
          onChanged();
        } else {
          loginBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .zkart.Login login = 1;</code>
       */
      public Builder clearLogin() {
        if (loginBuilder_ == null) {
          login_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          loginBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .zkart.Login login = 1;</code>
       */
      public Builder removeLogin(int index) {
        if (loginBuilder_ == null) {
          ensureLoginIsMutable();
          login_.remove(index);
          onChanged();
        } else {
          loginBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .zkart.Login login = 1;</code>
       */
      public com.zkartmod.LoginInfoProtos.Login.Builder getLoginBuilder(
          int index) {
        return getLoginFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .zkart.Login login = 1;</code>
       */
      public com.zkartmod.LoginInfoProtos.LoginOrBuilder getLoginOrBuilder(
          int index) {
        if (loginBuilder_ == null) {
          return login_.get(index);  } else {
          return loginBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .zkart.Login login = 1;</code>
       */
      public java.util.List<? extends com.zkartmod.LoginInfoProtos.LoginOrBuilder> 
           getLoginOrBuilderList() {
        if (loginBuilder_ != null) {
          return loginBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(login_);
        }
      }
      /**
       * <code>repeated .zkart.Login login = 1;</code>
       */
      public com.zkartmod.LoginInfoProtos.Login.Builder addLoginBuilder() {
        return getLoginFieldBuilder().addBuilder(
            com.zkartmod.LoginInfoProtos.Login.getDefaultInstance());
      }
      /**
       * <code>repeated .zkart.Login login = 1;</code>
       */
      public com.zkartmod.LoginInfoProtos.Login.Builder addLoginBuilder(
          int index) {
        return getLoginFieldBuilder().addBuilder(
            index, com.zkartmod.LoginInfoProtos.Login.getDefaultInstance());
      }
      /**
       * <code>repeated .zkart.Login login = 1;</code>
       */
      public java.util.List<com.zkartmod.LoginInfoProtos.Login.Builder> 
           getLoginBuilderList() {
        return getLoginFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zkartmod.LoginInfoProtos.Login, com.zkartmod.LoginInfoProtos.Login.Builder, com.zkartmod.LoginInfoProtos.LoginOrBuilder> 
          getLoginFieldBuilder() {
        if (loginBuilder_ == null) {
          loginBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.zkartmod.LoginInfoProtos.Login, com.zkartmod.LoginInfoProtos.Login.Builder, com.zkartmod.LoginInfoProtos.LoginOrBuilder>(
                  login_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          login_ = null;
        }
        return loginBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zkart.AllLoginInfo)
    }

    // @@protoc_insertion_point(class_scope:zkart.AllLoginInfo)
    private static final com.zkartmod.LoginInfoProtos.AllLoginInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zkartmod.LoginInfoProtos.AllLoginInfo();
    }

    public static com.zkartmod.LoginInfoProtos.AllLoginInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AllLoginInfo>
        PARSER = new com.google.protobuf.AbstractParser<AllLoginInfo>() {
      @java.lang.Override
      public AllLoginInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AllLoginInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AllLoginInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AllLoginInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zkartmod.LoginInfoProtos.AllLoginInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zkart_Login_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zkart_Login_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zkart_AllLoginInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zkart_AllLoginInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017logininfo.proto\022\005zkart\"3\n\005Login\022\n\n\002ID\030" +
      "\001 \001(\005\022\014\n\004mail\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\"+\n" +
      "\014AllLoginInfo\022\033\n\005login\030\001 \003(\0132\014.zkart.Log" +
      "inB\037\n\014com.zkartmodB\017LoginInfoProtosb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_zkart_Login_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_zkart_Login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zkart_Login_descriptor,
        new java.lang.String[] { "ID", "Mail", "Password", });
    internal_static_zkart_AllLoginInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_zkart_AllLoginInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zkart_AllLoginInfo_descriptor,
        new java.lang.String[] { "Login", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
