// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderdetails.proto

package com.zkartmod;

public final class OrderDetailsProtos {
  private OrderDetailsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InvoiceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zkart.Invoice)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string mail = 1;</code>
     * @return The mail.
     */
    java.lang.String getMail();
    /**
     * <code>string mail = 1;</code>
     * @return The bytes for mail.
     */
    com.google.protobuf.ByteString
        getMailBytes();

    /**
     * <code>repeated string orderDetails = 2;</code>
     * @return A list containing the orderDetails.
     */
    java.util.List<java.lang.String>
        getOrderDetailsList();
    /**
     * <code>repeated string orderDetails = 2;</code>
     * @return The count of orderDetails.
     */
    int getOrderDetailsCount();
    /**
     * <code>repeated string orderDetails = 2;</code>
     * @param index The index of the element to return.
     * @return The orderDetails at the given index.
     */
    java.lang.String getOrderDetails(int index);
    /**
     * <code>repeated string orderDetails = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the orderDetails at the given index.
     */
    com.google.protobuf.ByteString
        getOrderDetailsBytes(int index);
  }
  /**
   * Protobuf type {@code zkart.Invoice}
   */
  public  static final class Invoice extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zkart.Invoice)
      InvoiceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Invoice.newBuilder() to construct.
    private Invoice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Invoice() {
      mail_ = "";
      orderDetails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Invoice();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Invoice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              mail_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                orderDetails_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              orderDetails_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          orderDetails_ = orderDetails_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zkartmod.OrderDetailsProtos.internal_static_zkart_Invoice_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zkartmod.OrderDetailsProtos.internal_static_zkart_Invoice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zkartmod.OrderDetailsProtos.Invoice.class, com.zkartmod.OrderDetailsProtos.Invoice.Builder.class);
    }

    public static final int MAIL_FIELD_NUMBER = 1;
    private volatile java.lang.Object mail_;
    /**
     * <code>string mail = 1;</code>
     * @return The mail.
     */
    public java.lang.String getMail() {
      java.lang.Object ref = mail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mail_ = s;
        return s;
      }
    }
    /**
     * <code>string mail = 1;</code>
     * @return The bytes for mail.
     */
    public com.google.protobuf.ByteString
        getMailBytes() {
      java.lang.Object ref = mail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERDETAILS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList orderDetails_;
    /**
     * <code>repeated string orderDetails = 2;</code>
     * @return A list containing the orderDetails.
     */
    public com.google.protobuf.ProtocolStringList
        getOrderDetailsList() {
      return orderDetails_;
    }
    /**
     * <code>repeated string orderDetails = 2;</code>
     * @return The count of orderDetails.
     */
    public int getOrderDetailsCount() {
      return orderDetails_.size();
    }
    /**
     * <code>repeated string orderDetails = 2;</code>
     * @param index The index of the element to return.
     * @return The orderDetails at the given index.
     */
    public java.lang.String getOrderDetails(int index) {
      return orderDetails_.get(index);
    }
    /**
     * <code>repeated string orderDetails = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the orderDetails at the given index.
     */
    public com.google.protobuf.ByteString
        getOrderDetailsBytes(int index) {
      return orderDetails_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mail_);
      }
      for (int i = 0; i < orderDetails_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, orderDetails_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mail_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < orderDetails_.size(); i++) {
          dataSize += computeStringSizeNoTag(orderDetails_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getOrderDetailsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zkartmod.OrderDetailsProtos.Invoice)) {
        return super.equals(obj);
      }
      com.zkartmod.OrderDetailsProtos.Invoice other = (com.zkartmod.OrderDetailsProtos.Invoice) obj;

      if (!getMail()
          .equals(other.getMail())) return false;
      if (!getOrderDetailsList()
          .equals(other.getOrderDetailsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAIL_FIELD_NUMBER;
      hash = (53 * hash) + getMail().hashCode();
      if (getOrderDetailsCount() > 0) {
        hash = (37 * hash) + ORDERDETAILS_FIELD_NUMBER;
        hash = (53 * hash) + getOrderDetailsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zkartmod.OrderDetailsProtos.Invoice parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.OrderDetailsProtos.Invoice parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.OrderDetailsProtos.Invoice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.OrderDetailsProtos.Invoice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.OrderDetailsProtos.Invoice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.OrderDetailsProtos.Invoice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.OrderDetailsProtos.Invoice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zkartmod.OrderDetailsProtos.Invoice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkartmod.OrderDetailsProtos.Invoice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zkartmod.OrderDetailsProtos.Invoice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkartmod.OrderDetailsProtos.Invoice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zkartmod.OrderDetailsProtos.Invoice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zkartmod.OrderDetailsProtos.Invoice prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zkart.Invoice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zkart.Invoice)
        com.zkartmod.OrderDetailsProtos.InvoiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zkartmod.OrderDetailsProtos.internal_static_zkart_Invoice_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zkartmod.OrderDetailsProtos.internal_static_zkart_Invoice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zkartmod.OrderDetailsProtos.Invoice.class, com.zkartmod.OrderDetailsProtos.Invoice.Builder.class);
      }

      // Construct using com.zkartmod.OrderDetailsProtos.Invoice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mail_ = "";

        orderDetails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zkartmod.OrderDetailsProtos.internal_static_zkart_Invoice_descriptor;
      }

      @java.lang.Override
      public com.zkartmod.OrderDetailsProtos.Invoice getDefaultInstanceForType() {
        return com.zkartmod.OrderDetailsProtos.Invoice.getDefaultInstance();
      }

      @java.lang.Override
      public com.zkartmod.OrderDetailsProtos.Invoice build() {
        com.zkartmod.OrderDetailsProtos.Invoice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zkartmod.OrderDetailsProtos.Invoice buildPartial() {
        com.zkartmod.OrderDetailsProtos.Invoice result = new com.zkartmod.OrderDetailsProtos.Invoice(this);
        int from_bitField0_ = bitField0_;
        result.mail_ = mail_;
        if (((bitField0_ & 0x00000001) != 0)) {
          orderDetails_ = orderDetails_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.orderDetails_ = orderDetails_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zkartmod.OrderDetailsProtos.Invoice) {
          return mergeFrom((com.zkartmod.OrderDetailsProtos.Invoice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zkartmod.OrderDetailsProtos.Invoice other) {
        if (other == com.zkartmod.OrderDetailsProtos.Invoice.getDefaultInstance()) return this;
        if (!other.getMail().isEmpty()) {
          mail_ = other.mail_;
          onChanged();
        }
        if (!other.orderDetails_.isEmpty()) {
          if (orderDetails_.isEmpty()) {
            orderDetails_ = other.orderDetails_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOrderDetailsIsMutable();
            orderDetails_.addAll(other.orderDetails_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zkartmod.OrderDetailsProtos.Invoice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zkartmod.OrderDetailsProtos.Invoice) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object mail_ = "";
      /**
       * <code>string mail = 1;</code>
       * @return The mail.
       */
      public java.lang.String getMail() {
        java.lang.Object ref = mail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mail = 1;</code>
       * @return The bytes for mail.
       */
      public com.google.protobuf.ByteString
          getMailBytes() {
        java.lang.Object ref = mail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mail = 1;</code>
       * @param value The mail to set.
       * @return This builder for chaining.
       */
      public Builder setMail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mail = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMail() {
        
        mail_ = getDefaultInstance().getMail();
        onChanged();
        return this;
      }
      /**
       * <code>string mail = 1;</code>
       * @param value The bytes for mail to set.
       * @return This builder for chaining.
       */
      public Builder setMailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mail_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList orderDetails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureOrderDetailsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          orderDetails_ = new com.google.protobuf.LazyStringArrayList(orderDetails_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string orderDetails = 2;</code>
       * @return A list containing the orderDetails.
       */
      public com.google.protobuf.ProtocolStringList
          getOrderDetailsList() {
        return orderDetails_.getUnmodifiableView();
      }
      /**
       * <code>repeated string orderDetails = 2;</code>
       * @return The count of orderDetails.
       */
      public int getOrderDetailsCount() {
        return orderDetails_.size();
      }
      /**
       * <code>repeated string orderDetails = 2;</code>
       * @param index The index of the element to return.
       * @return The orderDetails at the given index.
       */
      public java.lang.String getOrderDetails(int index) {
        return orderDetails_.get(index);
      }
      /**
       * <code>repeated string orderDetails = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the orderDetails at the given index.
       */
      public com.google.protobuf.ByteString
          getOrderDetailsBytes(int index) {
        return orderDetails_.getByteString(index);
      }
      /**
       * <code>repeated string orderDetails = 2;</code>
       * @param index The index to set the value at.
       * @param value The orderDetails to set.
       * @return This builder for chaining.
       */
      public Builder setOrderDetails(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOrderDetailsIsMutable();
        orderDetails_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string orderDetails = 2;</code>
       * @param value The orderDetails to add.
       * @return This builder for chaining.
       */
      public Builder addOrderDetails(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOrderDetailsIsMutable();
        orderDetails_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string orderDetails = 2;</code>
       * @param values The orderDetails to add.
       * @return This builder for chaining.
       */
      public Builder addAllOrderDetails(
          java.lang.Iterable<java.lang.String> values) {
        ensureOrderDetailsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, orderDetails_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string orderDetails = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderDetails() {
        orderDetails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string orderDetails = 2;</code>
       * @param value The bytes of the orderDetails to add.
       * @return This builder for chaining.
       */
      public Builder addOrderDetailsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureOrderDetailsIsMutable();
        orderDetails_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zkart.Invoice)
    }

    // @@protoc_insertion_point(class_scope:zkart.Invoice)
    private static final com.zkartmod.OrderDetailsProtos.Invoice DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zkartmod.OrderDetailsProtos.Invoice();
    }

    public static com.zkartmod.OrderDetailsProtos.Invoice getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Invoice>
        PARSER = new com.google.protobuf.AbstractParser<Invoice>() {
      @java.lang.Override
      public Invoice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Invoice(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Invoice> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Invoice> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zkartmod.OrderDetailsProtos.Invoice getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zkart_Invoice_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zkart_Invoice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022orderdetails.proto\022\005zkart\"-\n\007Invoice\022\014" +
      "\n\004mail\030\001 \001(\t\022\024\n\014orderDetails\030\002 \003(\tB\"\n\014co" +
      "m.zkartmodB\022OrderDetailsProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_zkart_Invoice_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_zkart_Invoice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zkart_Invoice_descriptor,
        new java.lang.String[] { "Mail", "OrderDetails", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
