// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartdetails.proto

package com.zkartmod;

public final class CartDetailsProtos {
  private CartDetailsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProductOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zkartwebapp.Product)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 productId = 1;</code>
     * @return The productId.
     */
    int getProductId();

    /**
     * <code>int32 count = 2;</code>
     * @return The count.
     */
    int getCount();
  }
  /**
   * Protobuf type {@code zkartwebapp.Product}
   */
  public  static final class Product extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zkartwebapp.Product)
      ProductOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Product.newBuilder() to construct.
    private Product(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Product() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Product();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Product(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              productId_ = input.readInt32();
              break;
            }
            case 16: {

              count_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zkartmod.CartDetailsProtos.internal_static_zkartwebapp_Product_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zkartmod.CartDetailsProtos.internal_static_zkartwebapp_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zkartmod.CartDetailsProtos.Product.class, com.zkartmod.CartDetailsProtos.Product.Builder.class);
    }

    public static final int PRODUCTID_FIELD_NUMBER = 1;
    private int productId_;
    /**
     * <code>int32 productId = 1;</code>
     * @return The productId.
     */
    public int getProductId() {
      return productId_;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>int32 count = 2;</code>
     * @return The count.
     */
    public int getCount() {
      return count_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (productId_ != 0) {
        output.writeInt32(1, productId_);
      }
      if (count_ != 0) {
        output.writeInt32(2, count_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (productId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, productId_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zkartmod.CartDetailsProtos.Product)) {
        return super.equals(obj);
      }
      com.zkartmod.CartDetailsProtos.Product other = (com.zkartmod.CartDetailsProtos.Product) obj;

      if (getProductId()
          != other.getProductId()) return false;
      if (getCount()
          != other.getCount()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
      hash = (53 * hash) + getProductId();
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zkartmod.CartDetailsProtos.Product parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.CartDetailsProtos.Product parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.CartDetailsProtos.Product parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.CartDetailsProtos.Product parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.CartDetailsProtos.Product parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.CartDetailsProtos.Product parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.CartDetailsProtos.Product parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zkartmod.CartDetailsProtos.Product parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkartmod.CartDetailsProtos.Product parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zkartmod.CartDetailsProtos.Product parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkartmod.CartDetailsProtos.Product parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zkartmod.CartDetailsProtos.Product parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zkartmod.CartDetailsProtos.Product prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zkartwebapp.Product}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zkartwebapp.Product)
        com.zkartmod.CartDetailsProtos.ProductOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zkartmod.CartDetailsProtos.internal_static_zkartwebapp_Product_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zkartmod.CartDetailsProtos.internal_static_zkartwebapp_Product_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zkartmod.CartDetailsProtos.Product.class, com.zkartmod.CartDetailsProtos.Product.Builder.class);
      }

      // Construct using com.zkartmod.CartDetailsProtos.Product.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        productId_ = 0;

        count_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zkartmod.CartDetailsProtos.internal_static_zkartwebapp_Product_descriptor;
      }

      @java.lang.Override
      public com.zkartmod.CartDetailsProtos.Product getDefaultInstanceForType() {
        return com.zkartmod.CartDetailsProtos.Product.getDefaultInstance();
      }

      @java.lang.Override
      public com.zkartmod.CartDetailsProtos.Product build() {
        com.zkartmod.CartDetailsProtos.Product result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zkartmod.CartDetailsProtos.Product buildPartial() {
        com.zkartmod.CartDetailsProtos.Product result = new com.zkartmod.CartDetailsProtos.Product(this);
        result.productId_ = productId_;
        result.count_ = count_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zkartmod.CartDetailsProtos.Product) {
          return mergeFrom((com.zkartmod.CartDetailsProtos.Product)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zkartmod.CartDetailsProtos.Product other) {
        if (other == com.zkartmod.CartDetailsProtos.Product.getDefaultInstance()) return this;
        if (other.getProductId() != 0) {
          setProductId(other.getProductId());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zkartmod.CartDetailsProtos.Product parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zkartmod.CartDetailsProtos.Product) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int productId_ ;
      /**
       * <code>int32 productId = 1;</code>
       * @return The productId.
       */
      public int getProductId() {
        return productId_;
      }
      /**
       * <code>int32 productId = 1;</code>
       * @param value The productId to set.
       * @return This builder for chaining.
       */
      public Builder setProductId(int value) {
        
        productId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 productId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductId() {
        
        productId_ = 0;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>int32 count = 2;</code>
       * @return The count.
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>int32 count = 2;</code>
       * @param value The count to set.
       * @return This builder for chaining.
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 count = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zkartwebapp.Product)
    }

    // @@protoc_insertion_point(class_scope:zkartwebapp.Product)
    private static final com.zkartmod.CartDetailsProtos.Product DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zkartmod.CartDetailsProtos.Product();
    }

    public static com.zkartmod.CartDetailsProtos.Product getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Product>
        PARSER = new com.google.protobuf.AbstractParser<Product>() {
      @java.lang.Override
      public Product parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Product(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Product> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Product> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zkartmod.CartDetailsProtos.Product getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AllProductsInCartOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zkartwebapp.AllProductsInCart)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool cartEmpty = 1;</code>
     * @return The cartEmpty.
     */
    boolean getCartEmpty();

    /**
     * <code>repeated .zkartwebapp.Product prod = 2;</code>
     */
    java.util.List<com.zkartmod.CartDetailsProtos.Product> 
        getProdList();
    /**
     * <code>repeated .zkartwebapp.Product prod = 2;</code>
     */
    com.zkartmod.CartDetailsProtos.Product getProd(int index);
    /**
     * <code>repeated .zkartwebapp.Product prod = 2;</code>
     */
    int getProdCount();
    /**
     * <code>repeated .zkartwebapp.Product prod = 2;</code>
     */
    java.util.List<? extends com.zkartmod.CartDetailsProtos.ProductOrBuilder> 
        getProdOrBuilderList();
    /**
     * <code>repeated .zkartwebapp.Product prod = 2;</code>
     */
    com.zkartmod.CartDetailsProtos.ProductOrBuilder getProdOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code zkartwebapp.AllProductsInCart}
   */
  public  static final class AllProductsInCart extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zkartwebapp.AllProductsInCart)
      AllProductsInCartOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AllProductsInCart.newBuilder() to construct.
    private AllProductsInCart(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AllProductsInCart() {
      prod_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AllProductsInCart();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AllProductsInCart(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              cartEmpty_ = input.readBool();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                prod_ = new java.util.ArrayList<com.zkartmod.CartDetailsProtos.Product>();
                mutable_bitField0_ |= 0x00000001;
              }
              prod_.add(
                  input.readMessage(com.zkartmod.CartDetailsProtos.Product.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          prod_ = java.util.Collections.unmodifiableList(prod_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zkartmod.CartDetailsProtos.internal_static_zkartwebapp_AllProductsInCart_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zkartmod.CartDetailsProtos.internal_static_zkartwebapp_AllProductsInCart_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zkartmod.CartDetailsProtos.AllProductsInCart.class, com.zkartmod.CartDetailsProtos.AllProductsInCart.Builder.class);
    }

    public static final int CARTEMPTY_FIELD_NUMBER = 1;
    private boolean cartEmpty_;
    /**
     * <code>bool cartEmpty = 1;</code>
     * @return The cartEmpty.
     */
    public boolean getCartEmpty() {
      return cartEmpty_;
    }

    public static final int PROD_FIELD_NUMBER = 2;
    private java.util.List<com.zkartmod.CartDetailsProtos.Product> prod_;
    /**
     * <code>repeated .zkartwebapp.Product prod = 2;</code>
     */
    public java.util.List<com.zkartmod.CartDetailsProtos.Product> getProdList() {
      return prod_;
    }
    /**
     * <code>repeated .zkartwebapp.Product prod = 2;</code>
     */
    public java.util.List<? extends com.zkartmod.CartDetailsProtos.ProductOrBuilder> 
        getProdOrBuilderList() {
      return prod_;
    }
    /**
     * <code>repeated .zkartwebapp.Product prod = 2;</code>
     */
    public int getProdCount() {
      return prod_.size();
    }
    /**
     * <code>repeated .zkartwebapp.Product prod = 2;</code>
     */
    public com.zkartmod.CartDetailsProtos.Product getProd(int index) {
      return prod_.get(index);
    }
    /**
     * <code>repeated .zkartwebapp.Product prod = 2;</code>
     */
    public com.zkartmod.CartDetailsProtos.ProductOrBuilder getProdOrBuilder(
        int index) {
      return prod_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cartEmpty_ != false) {
        output.writeBool(1, cartEmpty_);
      }
      for (int i = 0; i < prod_.size(); i++) {
        output.writeMessage(2, prod_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cartEmpty_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, cartEmpty_);
      }
      for (int i = 0; i < prod_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, prod_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zkartmod.CartDetailsProtos.AllProductsInCart)) {
        return super.equals(obj);
      }
      com.zkartmod.CartDetailsProtos.AllProductsInCart other = (com.zkartmod.CartDetailsProtos.AllProductsInCart) obj;

      if (getCartEmpty()
          != other.getCartEmpty()) return false;
      if (!getProdList()
          .equals(other.getProdList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CARTEMPTY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCartEmpty());
      if (getProdCount() > 0) {
        hash = (37 * hash) + PROD_FIELD_NUMBER;
        hash = (53 * hash) + getProdList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zkartmod.CartDetailsProtos.AllProductsInCart parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.CartDetailsProtos.AllProductsInCart parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.CartDetailsProtos.AllProductsInCart parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.CartDetailsProtos.AllProductsInCart parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.CartDetailsProtos.AllProductsInCart parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.CartDetailsProtos.AllProductsInCart parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.CartDetailsProtos.AllProductsInCart parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zkartmod.CartDetailsProtos.AllProductsInCart parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkartmod.CartDetailsProtos.AllProductsInCart parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zkartmod.CartDetailsProtos.AllProductsInCart parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkartmod.CartDetailsProtos.AllProductsInCart parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zkartmod.CartDetailsProtos.AllProductsInCart parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zkartmod.CartDetailsProtos.AllProductsInCart prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zkartwebapp.AllProductsInCart}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zkartwebapp.AllProductsInCart)
        com.zkartmod.CartDetailsProtos.AllProductsInCartOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zkartmod.CartDetailsProtos.internal_static_zkartwebapp_AllProductsInCart_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zkartmod.CartDetailsProtos.internal_static_zkartwebapp_AllProductsInCart_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zkartmod.CartDetailsProtos.AllProductsInCart.class, com.zkartmod.CartDetailsProtos.AllProductsInCart.Builder.class);
      }

      // Construct using com.zkartmod.CartDetailsProtos.AllProductsInCart.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getProdFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cartEmpty_ = false;

        if (prodBuilder_ == null) {
          prod_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          prodBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zkartmod.CartDetailsProtos.internal_static_zkartwebapp_AllProductsInCart_descriptor;
      }

      @java.lang.Override
      public com.zkartmod.CartDetailsProtos.AllProductsInCart getDefaultInstanceForType() {
        return com.zkartmod.CartDetailsProtos.AllProductsInCart.getDefaultInstance();
      }

      @java.lang.Override
      public com.zkartmod.CartDetailsProtos.AllProductsInCart build() {
        com.zkartmod.CartDetailsProtos.AllProductsInCart result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zkartmod.CartDetailsProtos.AllProductsInCart buildPartial() {
        com.zkartmod.CartDetailsProtos.AllProductsInCart result = new com.zkartmod.CartDetailsProtos.AllProductsInCart(this);
        int from_bitField0_ = bitField0_;
        result.cartEmpty_ = cartEmpty_;
        if (prodBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            prod_ = java.util.Collections.unmodifiableList(prod_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.prod_ = prod_;
        } else {
          result.prod_ = prodBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zkartmod.CartDetailsProtos.AllProductsInCart) {
          return mergeFrom((com.zkartmod.CartDetailsProtos.AllProductsInCart)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zkartmod.CartDetailsProtos.AllProductsInCart other) {
        if (other == com.zkartmod.CartDetailsProtos.AllProductsInCart.getDefaultInstance()) return this;
        if (other.getCartEmpty() != false) {
          setCartEmpty(other.getCartEmpty());
        }
        if (prodBuilder_ == null) {
          if (!other.prod_.isEmpty()) {
            if (prod_.isEmpty()) {
              prod_ = other.prod_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureProdIsMutable();
              prod_.addAll(other.prod_);
            }
            onChanged();
          }
        } else {
          if (!other.prod_.isEmpty()) {
            if (prodBuilder_.isEmpty()) {
              prodBuilder_.dispose();
              prodBuilder_ = null;
              prod_ = other.prod_;
              bitField0_ = (bitField0_ & ~0x00000001);
              prodBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getProdFieldBuilder() : null;
            } else {
              prodBuilder_.addAllMessages(other.prod_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zkartmod.CartDetailsProtos.AllProductsInCart parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zkartmod.CartDetailsProtos.AllProductsInCart) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean cartEmpty_ ;
      /**
       * <code>bool cartEmpty = 1;</code>
       * @return The cartEmpty.
       */
      public boolean getCartEmpty() {
        return cartEmpty_;
      }
      /**
       * <code>bool cartEmpty = 1;</code>
       * @param value The cartEmpty to set.
       * @return This builder for chaining.
       */
      public Builder setCartEmpty(boolean value) {
        
        cartEmpty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool cartEmpty = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCartEmpty() {
        
        cartEmpty_ = false;
        onChanged();
        return this;
      }

      private java.util.List<com.zkartmod.CartDetailsProtos.Product> prod_ =
        java.util.Collections.emptyList();
      private void ensureProdIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          prod_ = new java.util.ArrayList<com.zkartmod.CartDetailsProtos.Product>(prod_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zkartmod.CartDetailsProtos.Product, com.zkartmod.CartDetailsProtos.Product.Builder, com.zkartmod.CartDetailsProtos.ProductOrBuilder> prodBuilder_;

      /**
       * <code>repeated .zkartwebapp.Product prod = 2;</code>
       */
      public java.util.List<com.zkartmod.CartDetailsProtos.Product> getProdList() {
        if (prodBuilder_ == null) {
          return java.util.Collections.unmodifiableList(prod_);
        } else {
          return prodBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .zkartwebapp.Product prod = 2;</code>
       */
      public int getProdCount() {
        if (prodBuilder_ == null) {
          return prod_.size();
        } else {
          return prodBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .zkartwebapp.Product prod = 2;</code>
       */
      public com.zkartmod.CartDetailsProtos.Product getProd(int index) {
        if (prodBuilder_ == null) {
          return prod_.get(index);
        } else {
          return prodBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .zkartwebapp.Product prod = 2;</code>
       */
      public Builder setProd(
          int index, com.zkartmod.CartDetailsProtos.Product value) {
        if (prodBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProdIsMutable();
          prod_.set(index, value);
          onChanged();
        } else {
          prodBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .zkartwebapp.Product prod = 2;</code>
       */
      public Builder setProd(
          int index, com.zkartmod.CartDetailsProtos.Product.Builder builderForValue) {
        if (prodBuilder_ == null) {
          ensureProdIsMutable();
          prod_.set(index, builderForValue.build());
          onChanged();
        } else {
          prodBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zkartwebapp.Product prod = 2;</code>
       */
      public Builder addProd(com.zkartmod.CartDetailsProtos.Product value) {
        if (prodBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProdIsMutable();
          prod_.add(value);
          onChanged();
        } else {
          prodBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .zkartwebapp.Product prod = 2;</code>
       */
      public Builder addProd(
          int index, com.zkartmod.CartDetailsProtos.Product value) {
        if (prodBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProdIsMutable();
          prod_.add(index, value);
          onChanged();
        } else {
          prodBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .zkartwebapp.Product prod = 2;</code>
       */
      public Builder addProd(
          com.zkartmod.CartDetailsProtos.Product.Builder builderForValue) {
        if (prodBuilder_ == null) {
          ensureProdIsMutable();
          prod_.add(builderForValue.build());
          onChanged();
        } else {
          prodBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zkartwebapp.Product prod = 2;</code>
       */
      public Builder addProd(
          int index, com.zkartmod.CartDetailsProtos.Product.Builder builderForValue) {
        if (prodBuilder_ == null) {
          ensureProdIsMutable();
          prod_.add(index, builderForValue.build());
          onChanged();
        } else {
          prodBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zkartwebapp.Product prod = 2;</code>
       */
      public Builder addAllProd(
          java.lang.Iterable<? extends com.zkartmod.CartDetailsProtos.Product> values) {
        if (prodBuilder_ == null) {
          ensureProdIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, prod_);
          onChanged();
        } else {
          prodBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .zkartwebapp.Product prod = 2;</code>
       */
      public Builder clearProd() {
        if (prodBuilder_ == null) {
          prod_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          prodBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .zkartwebapp.Product prod = 2;</code>
       */
      public Builder removeProd(int index) {
        if (prodBuilder_ == null) {
          ensureProdIsMutable();
          prod_.remove(index);
          onChanged();
        } else {
          prodBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .zkartwebapp.Product prod = 2;</code>
       */
      public com.zkartmod.CartDetailsProtos.Product.Builder getProdBuilder(
          int index) {
        return getProdFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .zkartwebapp.Product prod = 2;</code>
       */
      public com.zkartmod.CartDetailsProtos.ProductOrBuilder getProdOrBuilder(
          int index) {
        if (prodBuilder_ == null) {
          return prod_.get(index);  } else {
          return prodBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .zkartwebapp.Product prod = 2;</code>
       */
      public java.util.List<? extends com.zkartmod.CartDetailsProtos.ProductOrBuilder> 
           getProdOrBuilderList() {
        if (prodBuilder_ != null) {
          return prodBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(prod_);
        }
      }
      /**
       * <code>repeated .zkartwebapp.Product prod = 2;</code>
       */
      public com.zkartmod.CartDetailsProtos.Product.Builder addProdBuilder() {
        return getProdFieldBuilder().addBuilder(
            com.zkartmod.CartDetailsProtos.Product.getDefaultInstance());
      }
      /**
       * <code>repeated .zkartwebapp.Product prod = 2;</code>
       */
      public com.zkartmod.CartDetailsProtos.Product.Builder addProdBuilder(
          int index) {
        return getProdFieldBuilder().addBuilder(
            index, com.zkartmod.CartDetailsProtos.Product.getDefaultInstance());
      }
      /**
       * <code>repeated .zkartwebapp.Product prod = 2;</code>
       */
      public java.util.List<com.zkartmod.CartDetailsProtos.Product.Builder> 
           getProdBuilderList() {
        return getProdFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zkartmod.CartDetailsProtos.Product, com.zkartmod.CartDetailsProtos.Product.Builder, com.zkartmod.CartDetailsProtos.ProductOrBuilder> 
          getProdFieldBuilder() {
        if (prodBuilder_ == null) {
          prodBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.zkartmod.CartDetailsProtos.Product, com.zkartmod.CartDetailsProtos.Product.Builder, com.zkartmod.CartDetailsProtos.ProductOrBuilder>(
                  prod_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          prod_ = null;
        }
        return prodBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zkartwebapp.AllProductsInCart)
    }

    // @@protoc_insertion_point(class_scope:zkartwebapp.AllProductsInCart)
    private static final com.zkartmod.CartDetailsProtos.AllProductsInCart DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zkartmod.CartDetailsProtos.AllProductsInCart();
    }

    public static com.zkartmod.CartDetailsProtos.AllProductsInCart getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AllProductsInCart>
        PARSER = new com.google.protobuf.AbstractParser<AllProductsInCart>() {
      @java.lang.Override
      public AllProductsInCart parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AllProductsInCart(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AllProductsInCart> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AllProductsInCart> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zkartmod.CartDetailsProtos.AllProductsInCart getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zkartwebapp_Product_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zkartwebapp_Product_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zkartwebapp_AllProductsInCart_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zkartwebapp_AllProductsInCart_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021cartdetails.proto\022\013zkartwebapp\"+\n\007Prod" +
      "uct\022\021\n\tproductId\030\001 \001(\005\022\r\n\005count\030\002 \001(\005\"J\n" +
      "\021AllProductsInCart\022\021\n\tcartEmpty\030\001 \001(\010\022\"\n" +
      "\004prod\030\002 \003(\0132\024.zkartwebapp.ProductB!\n\014com" +
      ".zkartmodB\021CartDetailsProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_zkartwebapp_Product_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_zkartwebapp_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zkartwebapp_Product_descriptor,
        new java.lang.String[] { "ProductId", "Count", });
    internal_static_zkartwebapp_AllProductsInCart_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_zkartwebapp_AllProductsInCart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zkartwebapp_AllProductsInCart_descriptor,
        new java.lang.String[] { "CartEmpty", "Prod", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
