// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventorydetails.proto

package com.zkartmod;

public final class InventoryInfoProtos {
  private InventoryInfoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code zkartwebapp.productType}
   */
  public enum productType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MOBILE = 0;</code>
     */
    MOBILE(0),
    /**
     * <code>LAPTOP = 1;</code>
     */
    LAPTOP(1),
    /**
     * <code>TABLET = 2;</code>
     */
    TABLET(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MOBILE = 0;</code>
     */
    public static final int MOBILE_VALUE = 0;
    /**
     * <code>LAPTOP = 1;</code>
     */
    public static final int LAPTOP_VALUE = 1;
    /**
     * <code>TABLET = 2;</code>
     */
    public static final int TABLET_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static productType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static productType forNumber(int value) {
      switch (value) {
        case 0: return MOBILE;
        case 1: return LAPTOP;
        case 2: return TABLET;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<productType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        productType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<productType>() {
            public productType findValueByNumber(int number) {
              return productType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zkartmod.InventoryInfoProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final productType[] VALUES = values();

    public static productType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private productType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:zkartwebapp.productType)
  }

  public interface ProductOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zkartwebapp.Product)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 prodID = 1;</code>
     * @return The prodID.
     */
    int getProdID();

    /**
     * <code>.zkartwebapp.productType category = 2;</code>
     * @return The enum numeric value on the wire for category.
     */
    int getCategoryValue();
    /**
     * <code>.zkartwebapp.productType category = 2;</code>
     * @return The category.
     */
    com.zkartmod.InventoryInfoProtos.productType getCategory();

    /**
     * <code>string brand = 3;</code>
     * @return The brand.
     */
    java.lang.String getBrand();
    /**
     * <code>string brand = 3;</code>
     * @return The bytes for brand.
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>string model = 4;</code>
     * @return The model.
     */
    java.lang.String getModel();
    /**
     * <code>string model = 4;</code>
     * @return The bytes for model.
     */
    com.google.protobuf.ByteString
        getModelBytes();

    /**
     * <code>int64 price = 5;</code>
     * @return The price.
     */
    long getPrice();

    /**
     * <code>int32 stock = 6;</code>
     * @return The stock.
     */
    int getStock();

    /**
     * <code>string date = 7;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>string date = 7;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>int32 noOfDays = 8;</code>
     * @return The noOfDays.
     */
    int getNoOfDays();
  }
  /**
   * Protobuf type {@code zkartwebapp.Product}
   */
  public  static final class Product extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zkartwebapp.Product)
      ProductOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Product.newBuilder() to construct.
    private Product(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Product() {
      category_ = 0;
      brand_ = "";
      model_ = "";
      date_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Product();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Product(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              prodID_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              category_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              brand_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              model_ = s;
              break;
            }
            case 40: {

              price_ = input.readInt64();
              break;
            }
            case 48: {

              stock_ = input.readInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              date_ = s;
              break;
            }
            case 64: {

              noOfDays_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zkartmod.InventoryInfoProtos.internal_static_zkartwebapp_Product_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zkartmod.InventoryInfoProtos.internal_static_zkartwebapp_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zkartmod.InventoryInfoProtos.Product.class, com.zkartmod.InventoryInfoProtos.Product.Builder.class);
    }

    public static final int PRODID_FIELD_NUMBER = 1;
    private int prodID_;
    /**
     * <code>int32 prodID = 1;</code>
     * @return The prodID.
     */
    public int getProdID() {
      return prodID_;
    }

    public static final int CATEGORY_FIELD_NUMBER = 2;
    private int category_;
    /**
     * <code>.zkartwebapp.productType category = 2;</code>
     * @return The enum numeric value on the wire for category.
     */
    public int getCategoryValue() {
      return category_;
    }
    /**
     * <code>.zkartwebapp.productType category = 2;</code>
     * @return The category.
     */
    public com.zkartmod.InventoryInfoProtos.productType getCategory() {
      @SuppressWarnings("deprecation")
      com.zkartmod.InventoryInfoProtos.productType result = com.zkartmod.InventoryInfoProtos.productType.valueOf(category_);
      return result == null ? com.zkartmod.InventoryInfoProtos.productType.UNRECOGNIZED : result;
    }

    public static final int BRAND_FIELD_NUMBER = 3;
    private volatile java.lang.Object brand_;
    /**
     * <code>string brand = 3;</code>
     * @return The brand.
     */
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      }
    }
    /**
     * <code>string brand = 3;</code>
     * @return The bytes for brand.
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODEL_FIELD_NUMBER = 4;
    private volatile java.lang.Object model_;
    /**
     * <code>string model = 4;</code>
     * @return The model.
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      }
    }
    /**
     * <code>string model = 4;</code>
     * @return The bytes for model.
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 5;
    private long price_;
    /**
     * <code>int64 price = 5;</code>
     * @return The price.
     */
    public long getPrice() {
      return price_;
    }

    public static final int STOCK_FIELD_NUMBER = 6;
    private int stock_;
    /**
     * <code>int32 stock = 6;</code>
     * @return The stock.
     */
    public int getStock() {
      return stock_;
    }

    public static final int DATE_FIELD_NUMBER = 7;
    private volatile java.lang.Object date_;
    /**
     * <code>string date = 7;</code>
     * @return The date.
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 7;</code>
     * @return The bytes for date.
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOOFDAYS_FIELD_NUMBER = 8;
    private int noOfDays_;
    /**
     * <code>int32 noOfDays = 8;</code>
     * @return The noOfDays.
     */
    public int getNoOfDays() {
      return noOfDays_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (prodID_ != 0) {
        output.writeInt32(1, prodID_);
      }
      if (category_ != com.zkartmod.InventoryInfoProtos.productType.MOBILE.getNumber()) {
        output.writeEnum(2, category_);
      }
      if (!getBrandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, brand_);
      }
      if (!getModelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, model_);
      }
      if (price_ != 0L) {
        output.writeInt64(5, price_);
      }
      if (stock_ != 0) {
        output.writeInt32(6, stock_);
      }
      if (!getDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, date_);
      }
      if (noOfDays_ != 0) {
        output.writeInt32(8, noOfDays_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (prodID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, prodID_);
      }
      if (category_ != com.zkartmod.InventoryInfoProtos.productType.MOBILE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, category_);
      }
      if (!getBrandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, brand_);
      }
      if (!getModelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, model_);
      }
      if (price_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, price_);
      }
      if (stock_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, stock_);
      }
      if (!getDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, date_);
      }
      if (noOfDays_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, noOfDays_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zkartmod.InventoryInfoProtos.Product)) {
        return super.equals(obj);
      }
      com.zkartmod.InventoryInfoProtos.Product other = (com.zkartmod.InventoryInfoProtos.Product) obj;

      if (getProdID()
          != other.getProdID()) return false;
      if (category_ != other.category_) return false;
      if (!getBrand()
          .equals(other.getBrand())) return false;
      if (!getModel()
          .equals(other.getModel())) return false;
      if (getPrice()
          != other.getPrice()) return false;
      if (getStock()
          != other.getStock()) return false;
      if (!getDate()
          .equals(other.getDate())) return false;
      if (getNoOfDays()
          != other.getNoOfDays()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRODID_FIELD_NUMBER;
      hash = (53 * hash) + getProdID();
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + category_;
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + getBrand().hashCode();
      hash = (37 * hash) + MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getModel().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPrice());
      hash = (37 * hash) + STOCK_FIELD_NUMBER;
      hash = (53 * hash) + getStock();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (37 * hash) + NOOFDAYS_FIELD_NUMBER;
      hash = (53 * hash) + getNoOfDays();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zkartmod.InventoryInfoProtos.Product parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.InventoryInfoProtos.Product parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.InventoryInfoProtos.Product parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.InventoryInfoProtos.Product parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.InventoryInfoProtos.Product parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.InventoryInfoProtos.Product parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.InventoryInfoProtos.Product parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zkartmod.InventoryInfoProtos.Product parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkartmod.InventoryInfoProtos.Product parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zkartmod.InventoryInfoProtos.Product parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkartmod.InventoryInfoProtos.Product parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zkartmod.InventoryInfoProtos.Product parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zkartmod.InventoryInfoProtos.Product prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zkartwebapp.Product}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zkartwebapp.Product)
        com.zkartmod.InventoryInfoProtos.ProductOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zkartmod.InventoryInfoProtos.internal_static_zkartwebapp_Product_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zkartmod.InventoryInfoProtos.internal_static_zkartwebapp_Product_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zkartmod.InventoryInfoProtos.Product.class, com.zkartmod.InventoryInfoProtos.Product.Builder.class);
      }

      // Construct using com.zkartmod.InventoryInfoProtos.Product.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        prodID_ = 0;

        category_ = 0;

        brand_ = "";

        model_ = "";

        price_ = 0L;

        stock_ = 0;

        date_ = "";

        noOfDays_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zkartmod.InventoryInfoProtos.internal_static_zkartwebapp_Product_descriptor;
      }

      @java.lang.Override
      public com.zkartmod.InventoryInfoProtos.Product getDefaultInstanceForType() {
        return com.zkartmod.InventoryInfoProtos.Product.getDefaultInstance();
      }

      @java.lang.Override
      public com.zkartmod.InventoryInfoProtos.Product build() {
        com.zkartmod.InventoryInfoProtos.Product result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zkartmod.InventoryInfoProtos.Product buildPartial() {
        com.zkartmod.InventoryInfoProtos.Product result = new com.zkartmod.InventoryInfoProtos.Product(this);
        result.prodID_ = prodID_;
        result.category_ = category_;
        result.brand_ = brand_;
        result.model_ = model_;
        result.price_ = price_;
        result.stock_ = stock_;
        result.date_ = date_;
        result.noOfDays_ = noOfDays_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zkartmod.InventoryInfoProtos.Product) {
          return mergeFrom((com.zkartmod.InventoryInfoProtos.Product)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zkartmod.InventoryInfoProtos.Product other) {
        if (other == com.zkartmod.InventoryInfoProtos.Product.getDefaultInstance()) return this;
        if (other.getProdID() != 0) {
          setProdID(other.getProdID());
        }
        if (other.category_ != 0) {
          setCategoryValue(other.getCategoryValue());
        }
        if (!other.getBrand().isEmpty()) {
          brand_ = other.brand_;
          onChanged();
        }
        if (!other.getModel().isEmpty()) {
          model_ = other.model_;
          onChanged();
        }
        if (other.getPrice() != 0L) {
          setPrice(other.getPrice());
        }
        if (other.getStock() != 0) {
          setStock(other.getStock());
        }
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          onChanged();
        }
        if (other.getNoOfDays() != 0) {
          setNoOfDays(other.getNoOfDays());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zkartmod.InventoryInfoProtos.Product parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zkartmod.InventoryInfoProtos.Product) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int prodID_ ;
      /**
       * <code>int32 prodID = 1;</code>
       * @return The prodID.
       */
      public int getProdID() {
        return prodID_;
      }
      /**
       * <code>int32 prodID = 1;</code>
       * @param value The prodID to set.
       * @return This builder for chaining.
       */
      public Builder setProdID(int value) {
        
        prodID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 prodID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProdID() {
        
        prodID_ = 0;
        onChanged();
        return this;
      }

      private int category_ = 0;
      /**
       * <code>.zkartwebapp.productType category = 2;</code>
       * @return The enum numeric value on the wire for category.
       */
      public int getCategoryValue() {
        return category_;
      }
      /**
       * <code>.zkartwebapp.productType category = 2;</code>
       * @param value The enum numeric value on the wire for category to set.
       * @return This builder for chaining.
       */
      public Builder setCategoryValue(int value) {
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.zkartwebapp.productType category = 2;</code>
       * @return The category.
       */
      public com.zkartmod.InventoryInfoProtos.productType getCategory() {
        @SuppressWarnings("deprecation")
        com.zkartmod.InventoryInfoProtos.productType result = com.zkartmod.InventoryInfoProtos.productType.valueOf(category_);
        return result == null ? com.zkartmod.InventoryInfoProtos.productType.UNRECOGNIZED : result;
      }
      /**
       * <code>.zkartwebapp.productType category = 2;</code>
       * @param value The category to set.
       * @return This builder for chaining.
       */
      public Builder setCategory(com.zkartmod.InventoryInfoProtos.productType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        category_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.zkartwebapp.productType category = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCategory() {
        
        category_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object brand_ = "";
      /**
       * <code>string brand = 3;</code>
       * @return The brand.
       */
      public java.lang.String getBrand() {
        java.lang.Object ref = brand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          brand_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string brand = 3;</code>
       * @return The bytes for brand.
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        java.lang.Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string brand = 3;</code>
       * @param value The brand to set.
       * @return This builder for chaining.
       */
      public Builder setBrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrand() {
        
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 3;</code>
       * @param value The bytes for brand to set.
       * @return This builder for chaining.
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        brand_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object model_ = "";
      /**
       * <code>string model = 4;</code>
       * @return The model.
       */
      public java.lang.String getModel() {
        java.lang.Object ref = model_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          model_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string model = 4;</code>
       * @return The bytes for model.
       */
      public com.google.protobuf.ByteString
          getModelBytes() {
        java.lang.Object ref = model_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          model_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string model = 4;</code>
       * @param value The model to set.
       * @return This builder for chaining.
       */
      public Builder setModel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        model_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string model = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearModel() {
        
        model_ = getDefaultInstance().getModel();
        onChanged();
        return this;
      }
      /**
       * <code>string model = 4;</code>
       * @param value The bytes for model to set.
       * @return This builder for chaining.
       */
      public Builder setModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        model_ = value;
        onChanged();
        return this;
      }

      private long price_ ;
      /**
       * <code>int64 price = 5;</code>
       * @return The price.
       */
      public long getPrice() {
        return price_;
      }
      /**
       * <code>int64 price = 5;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(long value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 price = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        
        price_ = 0L;
        onChanged();
        return this;
      }

      private int stock_ ;
      /**
       * <code>int32 stock = 6;</code>
       * @return The stock.
       */
      public int getStock() {
        return stock_;
      }
      /**
       * <code>int32 stock = 6;</code>
       * @param value The stock to set.
       * @return This builder for chaining.
       */
      public Builder setStock(int value) {
        
        stock_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 stock = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearStock() {
        
        stock_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 7;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 7;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 7;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>string date = 7;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        date_ = value;
        onChanged();
        return this;
      }

      private int noOfDays_ ;
      /**
       * <code>int32 noOfDays = 8;</code>
       * @return The noOfDays.
       */
      public int getNoOfDays() {
        return noOfDays_;
      }
      /**
       * <code>int32 noOfDays = 8;</code>
       * @param value The noOfDays to set.
       * @return This builder for chaining.
       */
      public Builder setNoOfDays(int value) {
        
        noOfDays_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 noOfDays = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearNoOfDays() {
        
        noOfDays_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zkartwebapp.Product)
    }

    // @@protoc_insertion_point(class_scope:zkartwebapp.Product)
    private static final com.zkartmod.InventoryInfoProtos.Product DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zkartmod.InventoryInfoProtos.Product();
    }

    public static com.zkartmod.InventoryInfoProtos.Product getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Product>
        PARSER = new com.google.protobuf.AbstractParser<Product>() {
      @java.lang.Override
      public Product parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Product(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Product> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Product> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zkartmod.InventoryInfoProtos.Product getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProductsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zkartwebapp.Products)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .zkartwebapp.Product product = 1;</code>
     */
    java.util.List<com.zkartmod.InventoryInfoProtos.Product> 
        getProductList();
    /**
     * <code>repeated .zkartwebapp.Product product = 1;</code>
     */
    com.zkartmod.InventoryInfoProtos.Product getProduct(int index);
    /**
     * <code>repeated .zkartwebapp.Product product = 1;</code>
     */
    int getProductCount();
    /**
     * <code>repeated .zkartwebapp.Product product = 1;</code>
     */
    java.util.List<? extends com.zkartmod.InventoryInfoProtos.ProductOrBuilder> 
        getProductOrBuilderList();
    /**
     * <code>repeated .zkartwebapp.Product product = 1;</code>
     */
    com.zkartmod.InventoryInfoProtos.ProductOrBuilder getProductOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code zkartwebapp.Products}
   */
  public  static final class Products extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zkartwebapp.Products)
      ProductsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Products.newBuilder() to construct.
    private Products(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Products() {
      product_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Products();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Products(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                product_ = new java.util.ArrayList<com.zkartmod.InventoryInfoProtos.Product>();
                mutable_bitField0_ |= 0x00000001;
              }
              product_.add(
                  input.readMessage(com.zkartmod.InventoryInfoProtos.Product.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          product_ = java.util.Collections.unmodifiableList(product_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zkartmod.InventoryInfoProtos.internal_static_zkartwebapp_Products_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zkartmod.InventoryInfoProtos.internal_static_zkartwebapp_Products_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zkartmod.InventoryInfoProtos.Products.class, com.zkartmod.InventoryInfoProtos.Products.Builder.class);
    }

    public static final int PRODUCT_FIELD_NUMBER = 1;
    private java.util.List<com.zkartmod.InventoryInfoProtos.Product> product_;
    /**
     * <code>repeated .zkartwebapp.Product product = 1;</code>
     */
    public java.util.List<com.zkartmod.InventoryInfoProtos.Product> getProductList() {
      return product_;
    }
    /**
     * <code>repeated .zkartwebapp.Product product = 1;</code>
     */
    public java.util.List<? extends com.zkartmod.InventoryInfoProtos.ProductOrBuilder> 
        getProductOrBuilderList() {
      return product_;
    }
    /**
     * <code>repeated .zkartwebapp.Product product = 1;</code>
     */
    public int getProductCount() {
      return product_.size();
    }
    /**
     * <code>repeated .zkartwebapp.Product product = 1;</code>
     */
    public com.zkartmod.InventoryInfoProtos.Product getProduct(int index) {
      return product_.get(index);
    }
    /**
     * <code>repeated .zkartwebapp.Product product = 1;</code>
     */
    public com.zkartmod.InventoryInfoProtos.ProductOrBuilder getProductOrBuilder(
        int index) {
      return product_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < product_.size(); i++) {
        output.writeMessage(1, product_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < product_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, product_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zkartmod.InventoryInfoProtos.Products)) {
        return super.equals(obj);
      }
      com.zkartmod.InventoryInfoProtos.Products other = (com.zkartmod.InventoryInfoProtos.Products) obj;

      if (!getProductList()
          .equals(other.getProductList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getProductCount() > 0) {
        hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
        hash = (53 * hash) + getProductList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zkartmod.InventoryInfoProtos.Products parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.InventoryInfoProtos.Products parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.InventoryInfoProtos.Products parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.InventoryInfoProtos.Products parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.InventoryInfoProtos.Products parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkartmod.InventoryInfoProtos.Products parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkartmod.InventoryInfoProtos.Products parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zkartmod.InventoryInfoProtos.Products parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkartmod.InventoryInfoProtos.Products parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zkartmod.InventoryInfoProtos.Products parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkartmod.InventoryInfoProtos.Products parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zkartmod.InventoryInfoProtos.Products parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zkartmod.InventoryInfoProtos.Products prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zkartwebapp.Products}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zkartwebapp.Products)
        com.zkartmod.InventoryInfoProtos.ProductsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zkartmod.InventoryInfoProtos.internal_static_zkartwebapp_Products_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zkartmod.InventoryInfoProtos.internal_static_zkartwebapp_Products_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zkartmod.InventoryInfoProtos.Products.class, com.zkartmod.InventoryInfoProtos.Products.Builder.class);
      }

      // Construct using com.zkartmod.InventoryInfoProtos.Products.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getProductFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (productBuilder_ == null) {
          product_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          productBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zkartmod.InventoryInfoProtos.internal_static_zkartwebapp_Products_descriptor;
      }

      @java.lang.Override
      public com.zkartmod.InventoryInfoProtos.Products getDefaultInstanceForType() {
        return com.zkartmod.InventoryInfoProtos.Products.getDefaultInstance();
      }

      @java.lang.Override
      public com.zkartmod.InventoryInfoProtos.Products build() {
        com.zkartmod.InventoryInfoProtos.Products result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zkartmod.InventoryInfoProtos.Products buildPartial() {
        com.zkartmod.InventoryInfoProtos.Products result = new com.zkartmod.InventoryInfoProtos.Products(this);
        int from_bitField0_ = bitField0_;
        if (productBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            product_ = java.util.Collections.unmodifiableList(product_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.product_ = product_;
        } else {
          result.product_ = productBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zkartmod.InventoryInfoProtos.Products) {
          return mergeFrom((com.zkartmod.InventoryInfoProtos.Products)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zkartmod.InventoryInfoProtos.Products other) {
        if (other == com.zkartmod.InventoryInfoProtos.Products.getDefaultInstance()) return this;
        if (productBuilder_ == null) {
          if (!other.product_.isEmpty()) {
            if (product_.isEmpty()) {
              product_ = other.product_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureProductIsMutable();
              product_.addAll(other.product_);
            }
            onChanged();
          }
        } else {
          if (!other.product_.isEmpty()) {
            if (productBuilder_.isEmpty()) {
              productBuilder_.dispose();
              productBuilder_ = null;
              product_ = other.product_;
              bitField0_ = (bitField0_ & ~0x00000001);
              productBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getProductFieldBuilder() : null;
            } else {
              productBuilder_.addAllMessages(other.product_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zkartmod.InventoryInfoProtos.Products parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zkartmod.InventoryInfoProtos.Products) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.zkartmod.InventoryInfoProtos.Product> product_ =
        java.util.Collections.emptyList();
      private void ensureProductIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          product_ = new java.util.ArrayList<com.zkartmod.InventoryInfoProtos.Product>(product_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zkartmod.InventoryInfoProtos.Product, com.zkartmod.InventoryInfoProtos.Product.Builder, com.zkartmod.InventoryInfoProtos.ProductOrBuilder> productBuilder_;

      /**
       * <code>repeated .zkartwebapp.Product product = 1;</code>
       */
      public java.util.List<com.zkartmod.InventoryInfoProtos.Product> getProductList() {
        if (productBuilder_ == null) {
          return java.util.Collections.unmodifiableList(product_);
        } else {
          return productBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .zkartwebapp.Product product = 1;</code>
       */
      public int getProductCount() {
        if (productBuilder_ == null) {
          return product_.size();
        } else {
          return productBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .zkartwebapp.Product product = 1;</code>
       */
      public com.zkartmod.InventoryInfoProtos.Product getProduct(int index) {
        if (productBuilder_ == null) {
          return product_.get(index);
        } else {
          return productBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .zkartwebapp.Product product = 1;</code>
       */
      public Builder setProduct(
          int index, com.zkartmod.InventoryInfoProtos.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductIsMutable();
          product_.set(index, value);
          onChanged();
        } else {
          productBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .zkartwebapp.Product product = 1;</code>
       */
      public Builder setProduct(
          int index, com.zkartmod.InventoryInfoProtos.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.set(index, builderForValue.build());
          onChanged();
        } else {
          productBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zkartwebapp.Product product = 1;</code>
       */
      public Builder addProduct(com.zkartmod.InventoryInfoProtos.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductIsMutable();
          product_.add(value);
          onChanged();
        } else {
          productBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .zkartwebapp.Product product = 1;</code>
       */
      public Builder addProduct(
          int index, com.zkartmod.InventoryInfoProtos.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductIsMutable();
          product_.add(index, value);
          onChanged();
        } else {
          productBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .zkartwebapp.Product product = 1;</code>
       */
      public Builder addProduct(
          com.zkartmod.InventoryInfoProtos.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.add(builderForValue.build());
          onChanged();
        } else {
          productBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zkartwebapp.Product product = 1;</code>
       */
      public Builder addProduct(
          int index, com.zkartmod.InventoryInfoProtos.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.add(index, builderForValue.build());
          onChanged();
        } else {
          productBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zkartwebapp.Product product = 1;</code>
       */
      public Builder addAllProduct(
          java.lang.Iterable<? extends com.zkartmod.InventoryInfoProtos.Product> values) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, product_);
          onChanged();
        } else {
          productBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .zkartwebapp.Product product = 1;</code>
       */
      public Builder clearProduct() {
        if (productBuilder_ == null) {
          product_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          productBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .zkartwebapp.Product product = 1;</code>
       */
      public Builder removeProduct(int index) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.remove(index);
          onChanged();
        } else {
          productBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .zkartwebapp.Product product = 1;</code>
       */
      public com.zkartmod.InventoryInfoProtos.Product.Builder getProductBuilder(
          int index) {
        return getProductFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .zkartwebapp.Product product = 1;</code>
       */
      public com.zkartmod.InventoryInfoProtos.ProductOrBuilder getProductOrBuilder(
          int index) {
        if (productBuilder_ == null) {
          return product_.get(index);  } else {
          return productBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .zkartwebapp.Product product = 1;</code>
       */
      public java.util.List<? extends com.zkartmod.InventoryInfoProtos.ProductOrBuilder> 
           getProductOrBuilderList() {
        if (productBuilder_ != null) {
          return productBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(product_);
        }
      }
      /**
       * <code>repeated .zkartwebapp.Product product = 1;</code>
       */
      public com.zkartmod.InventoryInfoProtos.Product.Builder addProductBuilder() {
        return getProductFieldBuilder().addBuilder(
            com.zkartmod.InventoryInfoProtos.Product.getDefaultInstance());
      }
      /**
       * <code>repeated .zkartwebapp.Product product = 1;</code>
       */
      public com.zkartmod.InventoryInfoProtos.Product.Builder addProductBuilder(
          int index) {
        return getProductFieldBuilder().addBuilder(
            index, com.zkartmod.InventoryInfoProtos.Product.getDefaultInstance());
      }
      /**
       * <code>repeated .zkartwebapp.Product product = 1;</code>
       */
      public java.util.List<com.zkartmod.InventoryInfoProtos.Product.Builder> 
           getProductBuilderList() {
        return getProductFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zkartmod.InventoryInfoProtos.Product, com.zkartmod.InventoryInfoProtos.Product.Builder, com.zkartmod.InventoryInfoProtos.ProductOrBuilder> 
          getProductFieldBuilder() {
        if (productBuilder_ == null) {
          productBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.zkartmod.InventoryInfoProtos.Product, com.zkartmod.InventoryInfoProtos.Product.Builder, com.zkartmod.InventoryInfoProtos.ProductOrBuilder>(
                  product_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          product_ = null;
        }
        return productBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zkartwebapp.Products)
    }

    // @@protoc_insertion_point(class_scope:zkartwebapp.Products)
    private static final com.zkartmod.InventoryInfoProtos.Products DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zkartmod.InventoryInfoProtos.Products();
    }

    public static com.zkartmod.InventoryInfoProtos.Products getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Products>
        PARSER = new com.google.protobuf.AbstractParser<Products>() {
      @java.lang.Override
      public Products parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Products(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Products> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Products> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zkartmod.InventoryInfoProtos.Products getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zkartwebapp_Product_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zkartwebapp_Product_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zkartwebapp_Products_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zkartwebapp_Products_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026inventorydetails.proto\022\013zkartwebapp\"\241\001" +
      "\n\007Product\022\016\n\006prodID\030\001 \001(\005\022*\n\010category\030\002 " +
      "\001(\0162\030.zkartwebapp.productType\022\r\n\005brand\030\003" +
      " \001(\t\022\r\n\005model\030\004 \001(\t\022\r\n\005price\030\005 \001(\003\022\r\n\005st" +
      "ock\030\006 \001(\005\022\014\n\004date\030\007 \001(\t\022\020\n\010noOfDays\030\010 \001(" +
      "\005\"1\n\010Products\022%\n\007product\030\001 \003(\0132\024.zkartwe" +
      "bapp.Product*1\n\013productType\022\n\n\006MOBILE\020\000\022" +
      "\n\n\006LAPTOP\020\001\022\n\n\006TABLET\020\002B#\n\014com.zkartmodB" +
      "\023InventoryInfoProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_zkartwebapp_Product_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_zkartwebapp_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zkartwebapp_Product_descriptor,
        new java.lang.String[] { "ProdID", "Category", "Brand", "Model", "Price", "Stock", "Date", "NoOfDays", });
    internal_static_zkartwebapp_Products_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_zkartwebapp_Products_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zkartwebapp_Products_descriptor,
        new java.lang.String[] { "Product", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
